"""CWEval adapter (eval-only).

CWEval (Co1lin/CWEval, paper arXiv:2501.08200) ships as a flat per-task-
pair layout under `benchmark/core/<lang>/`:

    benchmark/core/py/cwe_020_0_task.py
    benchmark/core/py/cwe_020_0_test.py
    benchmark/core/py/cwe_022_0_task.py
    benchmark/core/py/cwe_022_0_test.py
    ...

Each `_task.<ext>` is a function skeleton with signature + docstring +
a `# BEGIN SOLUTION` / `// BEGIN SOLUTION` marker. The matching
`_test.<ext>` is the oracle script that the reliability oracle runs to
score model completions. The CWE id is encoded in the filename
(`cwe_NNN_M` where M is the variant index).

We extract:
  - CWE from filename (regex).
  - Function signature (first non-comment line for Python; the bracketed
    declaration for C/C++).
  - Docstring or block comment (everything between the signature and the
    BEGIN SOLUTION marker).

We do NOT include the reference solution in the prompt — the model
must generate one. The reliability oracle's CWEval execution path
(separate module, deferred) is responsible for invoking the _test file
on the model's completion.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterator, Optional

from ..reward.reliability_oracle import TestCase, TestSpec


# Harness template for Python CWEval prompts.
# Aliases the snippet (written by RealOracle as snippet.py) under the
# dataset's expected module name (e.g. cwe_020_0_task), then runs the
# dataset's test file (e.g. cwe_020_0_test.py) via pytest. Prints "PASS"
# iff every test passes; "FAIL" + brief diagnostics otherwise.
_CWEVAL_PY_HARNESS = '''"""CWEval Python harness.

Generated by data_prep/cweval.py CwevalAdapter. Edit there, not here.
"""
import importlib
import importlib.util
import shutil
import sys
import subprocess
import traceback
from pathlib import Path


def _alias_snippet():
    """Make the model's snippet.py importable as the dataset's task module."""
    snippet = Path("snippet.py")
    target = Path("{task_module}.py")
    if not snippet.exists():
        print("FAIL: snippet.py missing")
        sys.exit(1)
    if target.exists():
        target.unlink()
    shutil.copy(snippet, target)


def _find_pytest_python():
    """Find a Python interpreter with pytest installed. Try sys.executable
    first (in case RealOracle was wired to the project venv); otherwise
    walk the harness's containing dir up to a `.venv/bin/python`."""
    try:
        import pytest  # noqa: F401
        return sys.executable
    except ImportError:
        pass
    # Walk up from this harness file looking for a sibling .venv/
    here = Path(__file__).resolve()
    for parent in [here.parent] + list(here.parents):
        candidate = parent / ".venv" / "bin" / "python"
        if candidate.exists():
            return str(candidate)
    # Last resort: rely on PATH. Will fail loudly if no pytest.
    return sys.executable


def main():
    _alias_snippet()
    py = _find_pytest_python()
    try:
        proc = subprocess.run(
            [py, "-m", "pytest", "{test_module}.py",
             "-q", "--tb=no", "-p", "no:cacheprovider"],
            capture_output=True, text=True, timeout=25.0,
        )
    except subprocess.TimeoutExpired:
        print("FAIL: pytest timed out")
        sys.exit(1)
    except Exception:
        traceback.print_exc(file=sys.stderr)
        print("FAIL: pytest invocation raised")
        sys.exit(1)

    if proc.returncode == 0:
        print("PASS")
        sys.exit(0)
    else:
        print("FAIL")
        # Surface the last few lines so reward debugging is possible.
        for line in (proc.stdout + proc.stderr).strip().splitlines()[-5:]:
            print(f"  {{line}}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
'''
from .schema import (
    DataAdapter,
    Language,
    Prompt,
    make_prompt_id,
    normalize_cwe,
)

logger = logging.getLogger(__name__)


# Maps the directory name under benchmark/core/ to our Language enum.
# Default config includes Python + C + C++; Go and JS are filtered.
_DIRECTORY_LANGUAGE: dict[str, Language] = {
    "py": Language.PYTHON,
    "c": Language.C,
    "cpp": Language.CPP,
}

# CWEval filename conventions (verified against the real Co1lin/CWEval repo):
#   Python: cwe_<NUM>_<M>_task.py
#   C:      cwe_<NUM>_<M>_c_task.c
#   C++:    cwe_<NUM>_<M>_cpp_task.cpp
# The `_<lang>` suffix on C/C++ is optional; the regex accepts both forms.
_TASK_FILENAME_RE = re.compile(
    r"^cwe_(?P<cwe>\d+)_(?P<variant>\d+)(?:_(?P<langtag>c|cpp))?_task\.(?P<ext>py|c|cpp|h|hpp)$"
)

_EXT_LANGUAGE: dict[str, Language] = {
    "py": Language.PYTHON,
    "c": Language.C,
    "cpp": Language.CPP,
}


@dataclass
class CwevalConfig:
    cweval_root: Path
    languages: frozenset[Language] = field(
        default_factory=lambda: frozenset({Language.PYTHON, Language.C, Language.CPP})
    )
    target_cwes: Optional[frozenset[str]] = None
    dataset_version: str = "cweval-2501.08200"
    adapter_version: str = "0.2"  # bumped after on-disk-format rework


class CwevalAdapter(DataAdapter):
    def __init__(self, config: CwevalConfig) -> None:
        self.config = config

    @property
    def source_name(self) -> str:
        return "cweval"

    def load(self) -> Iterator[Prompt]:
        if not self.config.cweval_root.exists():
            raise FileNotFoundError(
                f"CWEval root does not exist: {self.config.cweval_root}"
            )

        core = self.config.cweval_root / "benchmark" / "core"
        if not core.exists():
            return

        for lang_dir in sorted(core.iterdir()):
            if not lang_dir.is_dir():
                continue
            language = _DIRECTORY_LANGUAGE.get(lang_dir.name)
            if language is None or language not in self.config.languages:
                continue

            for task_path in sorted(lang_dir.iterdir()):
                if not task_path.is_file():
                    continue
                m = _TASK_FILENAME_RE.match(task_path.name)
                if m is None:
                    continue

                ext = m.group("ext")
                # File ext can disagree with the directory's nominal lang
                # (e.g., header files in a c/ dir). Defer to the extension.
                ext_lang = _EXT_LANGUAGE.get(ext)
                if ext_lang is None or ext_lang not in self.config.languages:
                    continue

                # Filename is zero-padded (e.g. "020"); CWE id strips leading zeros.
                cwe = normalize_cwe(str(int(m.group("cwe"))))
                if self.config.target_cwes is not None and cwe not in self.config.target_cwes:
                    continue

                variant = m.group("variant")
                langtag = m.group("langtag")
                # Mirror the task file's lang-tag in the test filename, then
                # search for any matching extension (CWEval's C/C++ tests are
                # always `_test.py` despite the task file's `.c` / `.cpp`).
                cwe_padded = f"{int(m.group('cwe')):03d}"
                test_stem = (
                    f"cwe_{cwe_padded}_{variant}_{langtag}_test"
                    if langtag
                    else f"cwe_{cwe_padded}_{variant}_test"
                )
                test_path: Optional[Path] = None
                for test_ext in (".py", ".c", ".cpp"):
                    candidate = lang_dir / f"{test_stem}{test_ext}"
                    if candidate.exists():
                        test_path = candidate
                        break
                if test_path is None:
                    logger.debug(
                        "skipping %s: no matching test file (stem=%s)",
                        task_path.name, test_stem,
                    )
                    continue

                prompt = self._build_prompt(
                    task_path=task_path,
                    test_path=test_path,
                    cwe=cwe,
                    language=ext_lang,
                    variant=variant,
                )
                if prompt is not None:
                    yield prompt

    def _build_prompt(
        self,
        *,
        task_path: Path,
        test_path: Path,
        cwe: str,
        language: Language,
        variant: str,
    ) -> Optional[Prompt]:
        try:
            text = task_path.read_text(errors="replace")
        except OSError as exc:
            logger.warning("failed to read %s: %s", task_path, exc)
            return None

        signature, prompt_text, prefix_text, suffix_text = _split_prompt(text, language)
        if not prompt_text.strip():
            return None

        m = _TASK_FILENAME_RE.match(task_path.name)
        cwe_padded = f"{int(m.group('cwe')):03d}"
        langtag = m.group("langtag")
        task_id = (
            f"cwe_{cwe_padded}_{variant}_{langtag}" if langtag
            else f"cwe_{cwe_padded}_{variant}"
        )

        # For Python CWEval prompts, emit a pytest-driven harness that
        # makes the snippet importable under the dataset's expected module
        # name (e.g. `cwe_020_0_task`) and runs the dataset's
        # `cwe_NNN_M_test.py` test file via pytest. The harness reports
        # "PASS" iff every pytest test passes.
        #
        # C/C++ CWEval prompts are deferred — their test drivers are also
        # Python files but they invoke a compiled binary, which needs
        # additional wireup we haven't done. We DO populate prefix_text
        # and suffix_text on the TestSpec so that the oracle can splice
        # the model's body-only completion back into the original TU
        # (includes + helpers + main) before attempting to compile.
        test_spec = TestSpec(
            language=language,
            test_cases=[],
            prefix_text=prefix_text if language != Language.PYTHON else None,
            suffix_text=suffix_text if language != Language.PYTHON else None,
        )
        if language == Language.PYTHON and test_path.suffix == ".py":
            try:
                test_src = test_path.read_text(errors="replace")
            except OSError as exc:
                logger.warning("failed to read %s: %s", test_path, exc)
            else:
                test_module = test_path.stem      # e.g. "cwe_020_0_test"
                task_module = task_path.stem      # e.g. "cwe_020_0_task"
                harness = _CWEVAL_PY_HARNESS.format(
                    test_module=test_module,
                    task_module=task_module,
                )
                test_spec = TestSpec(
                    language=language,
                    test_cases=[TestCase(
                        input_stdin="",
                        expected_stdout="PASS",
                        timeout_s=30.0,
                    )],
                    extra_files={
                        f"{test_module}.py": test_src,
                        "_cweval_harness.py": harness,
                    },
                    entry_module="_cweval_harness",
                )

        return Prompt(
            id=make_prompt_id(self.source_name, task_id),
            source=self.source_name,
            language=language,
            target_cwe=cwe,
            prompt_text=prompt_text,
            test_spec=test_spec,
            task_signature=signature or None,
            metadata={
                "cweval_task_id": task_id,
                "oracle_script": str(test_path),
                "task_file": str(task_path),
                "dataset_version": self.config.dataset_version,
                "adapter_version": self.config.adapter_version,
            },
        )


def _split_prompt(
    text: str, language: Language
) -> tuple[str, str, Optional[str], Optional[str]]:
    """Return (signature, prompt_text, prefix_text, suffix_text).

    Marker conventions in CWEval (verified against the real Co1lin/CWEval):
      - Python: a single `# BEGIN SOLUTION` marker ends the prompt. The
        whole file up to (but not including) that line is the prompt
        (signature + docstring).
      - C / C++: a `// BEGIN PROMPT` marker delimits the *start* of the
        prompt (because the file has helper functions and includes
        before it). A `// BEGIN SOLUTION` marker ends the prompt.

    `prefix_text` is the file content *before* `BEGIN PROMPT` (the
    original includes + helper functions); `suffix_text` is the content
    *after* `BEGIN SOLUTION` (the helper main / driver). These are only
    populated for C / C++ (Python prompts run as a module, not as a
    standalone TU, so they don't need splice context). The oracle uses
    them in `_eval_c_family` to reattach the surrounding TU before
    compiling the model's body-only completion.
    """
    begin_prompt = re.compile(
        r"^[ \t]*(?://|/\*)\s*BEGIN PROMPT\b.*$", re.MULTILINE
    )
    begin_solution = re.compile(
        r"^[ \t]*(?:#|//|/\*)\s*BEGIN SOLUTION\b.*$", re.MULTILINE
    )

    start = 0
    prefix_text: Optional[str] = None
    if language != Language.PYTHON:
        m_start = begin_prompt.search(text)
        if m_start is not None:
            # Everything up to and including the BEGIN PROMPT line is
            # the prefix the model will not see but the compiler needs:
            # includes, typedefs, helpers, etc.
            prefix_end = m_start.end()
            # Capture through the newline after BEGIN PROMPT (if any) so
            # the prefix ends cleanly at a line boundary.
            if prefix_end < len(text) and text[prefix_end] == "\n":
                prefix_end += 1
            prefix_text = text[:prefix_end]
            # Slice from the line AFTER the BEGIN PROMPT marker.
            start = prefix_end

    end = len(text)
    suffix_text: Optional[str] = None
    m_end = begin_solution.search(text, pos=start)
    if m_end is not None:
        end = m_end.start()
        if language != Language.PYTHON:
            # The text after BEGIN SOLUTION contains the dataset's
            # reference implementation (which the model is replacing)
            # followed by trailing main()/driver code. To splice cleanly
            # we want to drop the reference body and keep the trailing
            # code. Brace-balance from BEGIN SOLUTION forward: at this
            # point the function is mid-body (one open brace from
            # BEGIN PROMPT), so we count `depth = 1` and walk to the
            # matching `}` to find the end of the function. Everything
            # after that `}` is the suffix to splice back in.
            depth = 1
            i = m_end.end()
            n = len(text)
            close_idx = None
            in_line_comment = False
            in_block_comment = False
            in_string = False
            string_char = ""
            while i < n:
                c = text[i]
                nxt = text[i + 1] if i + 1 < n else ""
                if in_line_comment:
                    if c == "\n":
                        in_line_comment = False
                elif in_block_comment:
                    if c == "*" and nxt == "/":
                        in_block_comment = False
                        i += 1
                elif in_string:
                    if c == "\\" and nxt:
                        i += 1
                    elif c == string_char:
                        in_string = False
                else:
                    if c == "/" and nxt == "/":
                        in_line_comment = True
                        i += 1
                    elif c == "/" and nxt == "*":
                        in_block_comment = True
                        i += 1
                    elif c in ("'", '"'):
                        in_string = True
                        string_char = c
                    elif c == "{":
                        depth += 1
                    elif c == "}":
                        depth -= 1
                        if depth == 0:
                            close_idx = i
                            break
                i += 1
            if close_idx is not None:
                # Keep the closing `}` (so the spliced function is
                # complete) plus everything after it (trailing main/
                # driver, etc.).
                suffix_text = text[close_idx:]
            else:
                # Fallback: include everything from BEGIN SOLUTION as
                # the suffix. Better than dropping it entirely — at
                # worst the compile fails the way it would have without
                # the splice.
                suffix_text = text[m_end.start():]

    prompt_text = text[start:end].rstrip() + "\n"

    signature = ""
    lines = prompt_text.splitlines()
    if language == Language.PYTHON:
        for line in lines:
            s = line.strip()
            if s.startswith("def ") or s.startswith("async def "):
                signature = s
                break
    else:
        # C / C++: signature usually has '(' and ends with '{' or ';'.
        for line in lines:
            s = line.strip()
            if not s or s.startswith("//") or s.startswith("/*") or s.startswith("*"):
                continue
            if "(" in s:
                signature = s.rstrip("{").strip()
                break

    return signature, prompt_text, prefix_text, suffix_text
